spring.application.name=gestoracademico

app.cookie.secure=true
app.cookie.sameSite=Strict

# ==========================
# DATASOURCE (MariaDB)
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ==========================
# JWT
# ==========================
jwt.secret=${JWT_SECRET}
jwt.expiration.ms=${JWT_EXPIRATION}

# ==========================
# ACTUATOR (para healthchecks)
# ==========================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
